### ISSUE TITLE
How could I exclude some files from report?

### ISSUE THREAD

**Issue by oktonion** [codecov/codecov-python#282]
Hello, I'm using Travis CI and codecov.io in my project build setup.

My .travis.yml looks like

```
...
    - os: linux
      compiler: gcc
      dist: precise
      env:
      - COMPILER=g++
      - CODE_COVERAGE_LIBS=-lgcov
      - CODE_COVERAGE_FLAGS=--coverage -fprofile-arcs -ftest-coverage
      - BUILD_LIB_SCRIPT="./build_lib.sh"
      - BUILD_SCRIPT="./build_tests.sh"
      - RUN_SCRIPT="./run_tests.sh"
      before_install: 
      - sudo pip install codecov
      after_success:
      - chmod +x ./get_code_cov.sh
      - ./get_code_cov.sh
      - codecov
...
```

the `get_code_cov.sh` script is simple as:

```
#!/bin/bash

for file in ./tests/bin/*; do
    gcov $file.gcda
done
```

Now I wonder: how could I make `codecov` to exclude files with patterns like "tests/*" from the generated report?
